version: '3'

services:
  homekeeper-link-server:
    build:
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "25534:25534"
    networks:
      - main-network
    environment:
      - MONGO_SRV=${MONGO_SRV}
      - MONGO_DB=${MONGO_DB}
      - PORT=${PORT}
      - ADDRESS=${ADDRESS}
      - NOTIFY_INTERVAL=${NOTIFY_INTERVAL}
      - TL_TOKEN=${TL_TOKEN}
      - CHAT_ID=${CHAT_ID}

networks:
  main-network:
    driver: bridge